voxpop/urls.py
from django.urls import path
from ninja import NinjaAPI

from . import views
from voxpop.api import router as voxpop_router

api = NinjaAPI(urls_namespace="voxpop:api")

api.add_router("/voxpops/", voxpop_router)

app_name = "voxpop"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path(
        "voxpops/<uuid:voxpop_id>/questions/new",
        views.new_question,
        name="new_question",
    ),
    path(
        "voxpops/<uuid:voxpop_id>/questions/stream",
        views.questions_stream_view,
        {"channel_prefix": ""},
        name="stream_questions",
    ),
    path("api/", api.urls),
    path("admin/", views.admin_index, name="admin"),
    path("admin/voxpops/new", views.new_voxpop, name="new_voxpop"),
    path("admin/voxpops/<uuid:voxpop_id>/edit", views.edit_voxpop, name="edit_voxpop"),
    path("admin/voxpops/<uuid:voxpop_id>/", views.admin_voxpop, name="admin_voxpop"),
    path(
        "admin/voxpops/<uuid:voxpop_id>/<uuid:question_id>",
        views.admin_question_set_state,
        name="admin_question_set_state",
    ),
    path(
        "admin/voxpops/<uuid:voxpop_id>/questions/stream",
        views.questions_stream_view,
        {"channel_prefix": "admin_"},
        name="admin_questions_stream",
    ),
]

voxpop_project/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

## See here this for Django-Ninja when using applications.
## https://django-ninja.rest-framework.com/guides/routers/

urlpatterns = [
    path("", include("voxpop.urls")),
    path("djangoadmin/", admin.site.urls),
]

voxpop/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _


class UUIDModel(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    class Meta:
        abstract = True


class CreatedUpdatedMixin(UUIDModel):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Organisation(CreatedUpdatedMixin):
    # Work in progress.
    name = models.CharField(max_length=200)
    hostname = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )
    idp = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )
    admin_group = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class Voxpop(CreatedUpdatedMixin):
    title = models.CharField(_("title"), max_length=50)
    description = models.TextField(_("description"), blank=True)
    created_by = models.CharField(_("created by"), max_length=50)
    starts_at = models.DateTimeField(_("start time"))
    expires_at = models.DateTimeField(_("end time"))
    is_moderated = models.BooleanField(_("is moderated"), default=True)
    allow_anonymous = models.BooleanField(_("allow anonymous"), default=True)
    organisation = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        related_name="voxpops",
    )

    def __str__(self):
        return f"{self.title}"


class Question(CreatedUpdatedMixin):
    class State(models.TextChoices):
        NEW = "new", _("New")
        APPROVED = "approved", _("Approved")
        ANSWERED = "answered", _("Answered")
        DISCARDED = "discarded", _("Discarded")

    text = models.TextField(max_length=1000)
    state = models.CharField(
        max_length=9,
        choices=State.choices,
        default=State.NEW,
    )
    created_by = models.CharField(max_length=200)
    display_name = models.CharField(blank=True, max_length=50)
    voxpop = models.ForeignKey(
        Voxpop,
        on_delete=models.CASCADE,
        related_name="questions",
    )

    def approve(self):
        self.state = self.State.APPROVED
        self.save()

    def __str__(self):
        return f'[{self.created_at.strftime("%H:%M")}] "{self.text}"'


class Vote(CreatedUpdatedMixin):
    created_by = models.CharField(max_length=200)
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="votes",
    )

    def __str__(self):
        return f'{self.created_by} -> "{self.question.text}"'


class Message(models.Model):
    voxpop = models.ForeignKey(
        Voxpop,
        on_delete=models.CASCADE,
        related_name="messages",
    )
    channel_name = models.CharField(max_length=255, default="")
    event = models.CharField(max_length=255)
    data = models.TextField()

    def __str__(self):
        return f"id: {self.id}\nevent: {self.event}\ndata: {self.data}\n\n"

voxpop/forms.py
from django import forms

from .models import Question
from .models import Voxpop


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = [
            "text",
            "display_name",
        ]


class VoxpopForm(forms.ModelForm):
    class Meta:
        model = Voxpop
        fields = [
            "title",
            "description",
            "starts_at",
            "expires_at",
            "is_moderated",
            "allow_anonymous",
        ]

        widgets = {
            "description": forms.Textarea(attrs={"rows": 5}),
            "starts_at": forms.DateInput(
                attrs={"type": "datetime-local"},
                format="%Y-%m-%d %H:%M",
            ),
            "expires_at": forms.DateInput(
                attrs={"type": "datetime-local"},
                format="%Y-%m-%d %H:%M",
            ),
        }

voxpop/views.py
from collections.abc import AsyncIterator
from uuid import UUID

import jwt
from django.conf import settings
from django.contrib import messages
from django.db import close_old_connections
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import StreamingHttpResponse
from django.shortcuts import Http404
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from .forms import QuestionForm
from .forms import VoxpopForm
from .models import Question
from .selectors import current_organisation
from .selectors import get_messages
from .selectors import get_questions
from .selectors import get_voxpop
from .selectors import get_voxpops
from .services import create_question
from .services import create_voxpop
from .utils import get_async_redis_connection
from .utils import get_notify_channel_name


def is_admin(request):
    return request.session.get("admin")


def admin_index(request):
    organisation = current_organisation(request)
    if is_admin(request):
        if organisation:
            context = {
                "voxpops": get_voxpops(organisation),
                "organisation": organisation,
            }
        else:
            messages.warning(
                request,
                "Der findes ingen organisation til dette hostnavn!",
            )
            context = {"organisation": organisation}
        return render(request, "voxpop/admin/index.html", context)

    # TODO: Handle non-admin user request to "/admin"?
    # return render(request, "voxpop/admin/auth_error.html")

    token = request.GET.get("token", False)
    if token:
        try:
            payload = jwt.decode(
                token,
                settings.SHARED_SECRET_JWT,
                algorithms=["HS256"],
            )

        except jwt.exceptions.InvalidSignatureError:
            msg = _("invalid signature")
            return render(
                request,
                "voxpop/admin/auth_error.html",
                {"error": msg},
            )

        except jwt.exceptions.DecodeError:
            msg = _("jwt decode error")
            return render(
                request,
                "voxpop/admin/auth_error.html",
                {"error": msg},
            )
        try:
            request.session["display_name"] = payload["display_name"]
            request.session["unique_name"] = payload["unique_name"]
            request.session["admin"] = payload["admin"]
        except KeyError:
            return {"msg": "Mandatory attribute(s) missing."}
        return redirect("/admin")

    idp_url = organisation.idp + "?url=https://" + request.get_host()
    return redirect(idp_url)


def admin_voxpop(request, voxpop_id: UUID = None):
    if is_admin(request):
        if voxpop_id:
            voxpop = get_voxpop(voxpop_id=voxpop_id)
            context = {
                "voxpop": voxpop,
                "questions": {
                    "new": get_questions(
                        voxpop=voxpop,
                        state=Question.State.NEW,
                    ),
                    "approved": get_questions(
                        voxpop=voxpop,
                        state=Question.State.APPROVED,
                    ),
                    "answered": get_questions(
                        voxpop=voxpop,
                        state=Question.State.ANSWERED,
                    ),
                    "discarded": get_questions(
                        voxpop=voxpop,
                        state=Question.State.DISCARDED,
                    ),
                },
                "idp": voxpop.organisation.idp,
            }
            return render(request, "voxpop/admin/voxpop.html", context)
    return render(request, "voxpop/admin/auth_error.html")


def admin_question_set_state(request, voxpop_id, question_id):
    if is_admin(request):
        new_state = request.GET.get("state", None)
        question = Question.objects.get(uuid=question_id)
        question.state = new_state
        question.save()
        return HttpResponse(status=204)


def new_voxpop(request):
    if is_admin(request):
        if request.method == "GET":
            context = {
                "form": VoxpopForm(),
            }
            return render(request, "voxpop/admin/new_voxpop.html", context)
        if request.method == "POST":
            form = VoxpopForm(request.POST)
            if form.is_valid():
                formdata = form.save(commit=False)
                create_voxpop(
                    formdata.title,
                    formdata.description,
                    request.session["unique_name"],
                    formdata.starts_at,
                    formdata.expires_at,
                    formdata.is_moderated,
                    formdata.allow_anonymous,
                    current_organisation(request),
                )
                return redirect("/admin")
            else:
                print("Form invalid")
            return redirect("/admin/voxpops/new")
    return render(request, "voxpop/admin/auth_error.html")


def edit_voxpop(request, voxpop_id: UUID = None):
    if is_admin(request):
        voxpop = get_voxpop(voxpop_id)
        if request.method == "GET":
            context = {
                "voxpop": voxpop,
                "form": VoxpopForm(instance=voxpop),
            }
            return render(request, "voxpop/admin/edit_voxpop.html", context)

        if request.method == "POST":
            form = VoxpopForm(request.POST, instance=voxpop)
            form.save(commit=True)
            return redirect(f"/admin/voxpops/{voxpop_id}/")


def index(request):
    org = current_organisation(request)
    context = {}
    context["current_organisation"] = org
    context["voxpop_id"] = ""
    context["allow_anonymous"] = False
    if org:
        voxpop = get_voxpops(org).filter(is_active=True).order_by("starts_at").last()
        if voxpop:
            context = {
                "voxpop": voxpop,
                "idp": voxpop.organisation.idp,
            }
    return render(request, "voxpop/index.html", context)


def detail(request, question_id: UUID):
    try:
        question = get_questions(question_id=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    context = {
        "question": question,
        "id": question.uuid,
    }
    return render(request, "voxpop/detail.html", context)


def new_question(request: HttpRequest, voxpop_id: UUID) -> HttpResponse:
    voxpop = get_voxpop(voxpop_id=voxpop_id)
    form = QuestionForm
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            formdata = form.save(commit=False)
            create_question(
                formdata.text,
                request.session.session_key,
                formdata.display_name,
                voxpop_id,
            )
            if voxpop.is_moderated:
                messages.info(request, "Dit spørgsmål er nu sendt til godkendelse.")
            return redirect("voxpop:index")
        else:
            return HttpResponse("Ukendt fejl, prøv venligst igen.")

    return render(
        request,
        "voxpop/question.html",
        {"form": form, "allow_anonymous": voxpop.allow_anonymous},
    )


async def __stream_questions(
    *,
    channel_prefix: str,
    voxpop_id: UUID,
    last_event_id: int,
) -> AsyncIterator[str]:
    channel_name = get_notify_channel_name(
        channel_prefix=channel_prefix,
        voxpop_id=voxpop_id,
    )
    if last_event_id > 0:  # Reconnect request
        missed_messages = await get_messages(channel_name, last_event_id)
        if len(missed_messages) == 0:  # Send a dummy response to activate the stream.
            yield "event: ping\ndata: Pong\n\n"
        else:
            yield "".join([str(m) for m in missed_messages])
    else:  # Send a dummy response to activate the stream.
        yield "event: ping\ndata: Pong\n\n"

    # Since we are using a streaming response, we need to close the old connection
    # ourselves. Otherwise, the connection will remain open until the request_finished
    # signal is sent, which might take a while.
    close_old_connections()

    # Get an async redis connection.
    redis_client = get_async_redis_connection()
    # Use the redis pubsub interface.
    async with redis_client.pubsub() as pubsub:
        # Subscribe to the channel.
        await pubsub.subscribe(channel_name)
        # Listen for messages.
        async for message in pubsub.listen():
            # We only care about messages of the type "message" (not "subscribe" etc.)
            if message["type"] == "message":
                # Yield the message data to the client.
                yield message["data"].decode()


async def questions_stream_view(
    request: HttpRequest,
    channel_prefix: str,
    voxpop_id: UUID,
) -> StreamingHttpResponse:
    last_event_id = int(request.headers.get("Last-Event-Id", 0))
    return StreamingHttpResponse(
        content_type="text/event-stream",
        headers={
            "X-Accel-Buffering": "no",
            "Access-Control-Allow-Credentials": "true",
            "Cache-Control": "No-Cache",
        },
        streaming_content=__stream_questions(
            channel_prefix=channel_prefix,
            voxpop_id=voxpop_id,
            last_event_id=last_event_id,
        ),
    )

voxpop/templates/voxpop/admin/auth_error.html
{% extends 'layout.html' %}
{% load i18n %}
{% block title %}{% trans "error"|capfirst %}{% endblock %}
{% block content %}
<div id="errormessage">
	<h2>{% trans "401 Unauthorized" %}</h2>
	{% if error %}
	<h4> {{ error|title }} </h4>
	{% endif %}
</div>
{% endblock %}

voxpop/templates/voxpop/admin/edit_voxpop.html
{% extends 'admin-layout.html' %}
{% load i18n %}
{% block title %}{{ voxpop }}{% endblock %}
{% block content %}
<h1>{% trans "now editing Voxpop"|capfirst %}: "{{ voxpop }}"</h1>
<form action="{% url 'voxpop:edit_voxpop' voxpop_id=voxpop.uuid %}" method="POST">
	{% csrf_token %}
	{% for field in form %}
	{{ field.label }}
	{{ field }}
	{% endfor %}
	<button type="submit">{% trans "done"|capfirst %}</button>
</form>
<p><a href="{% url 'voxpop:admin' %}">{% trans "return"|capfirst %}</a></p>
{% endblock %}

voxpop/templates/voxpop/admin/index.html
{% extends 'admin-layout.html' %}
{% load i18n %}
{% block title %}{% trans "voxpop admin interface"|capfirst %}{% endblock %}
{% block content %}
	<h2>Voxpops</h2>
	{% if organisation != None %}
	<p><a href="{% url 'voxpop:new_voxpop' %}" role="button">{% trans "create new"|capfirst %}</a></p>
	<ul>{% for voxpop in voxpops %}
	    <li>
			<a href="{% url 'voxpop:admin_voxpop' voxpop.uuid %}">{{ voxpop.title }}</a> - {{ voxpop.question_count }} {% trans "question(s)" %}.
		{% if voxpop.is_active %} &#128994; {% endif %}
		<p>{{ voxpop.description }}</p>
	    </li>
	{% endfor %}</ul>
	{% endif %}
{% endblock %}

voxpop/templates/voxpop/admin/new_voxpop.html
{% extends 'admin-layout.html' %}
{% load i18n %}
{% block title %}Opret voxpop - Voxpop Admin Interface{% endblock %}
{% block content %}
<h1>{% trans "create new Voxpop"|capfirst %}</h1>
  <form action="{% url 'voxpop:new_voxpop' %}" method="POST">
	{% csrf_token %}
	{% for field in form %}
	{{ field.label_tag }}
	{{ field }}
	{% endfor %}
	<p><button type="submit">{% trans "create"|capfirst %}</button></p>
  </form>
  <p><a href="{% url 'voxpop:admin' %}">{% trans "return"|capfirst %}</a></p>
{% endblock %}

voxpop/templates/voxpop/admin/voxpop.html
{% extends 'admin-layout.html' %}
{% load i18n %}
{% block title %}{{ voxpop.title }} - Voxpop Admin Interface{% endblock %}
{% block content %}
<h1>{{ voxpop.title }}</h1>
			<div id="description">
				<p>{{ voxpop.description }} </p>
				<p>{{ voxpop.starts_at }} - {{ voxpop.expires_at }} </p>
				<p><a href="edit" role="button">{% trans "edit"|capfirst %}</a></p>
			</div>
			<div id="adminQuestionLists" data-voxpop-uuid="{{ voxpop.uuid }}"{% if voxpop.is_moderated %} data-voxpop-is-moderated{% endif %}>
				{% csrf_token %}
				{% for key, values in questions.items %}
				<details{% if key == "new" or key == "approved" or key == "answered" and not voxpop.is_moderated %} open{% endif %}>
					<summary>{% trans key|capfirst %}</summary>
					<div id="{{ key }}Questions">{% for question in values %}
						<div data-voxpop-question-uuid="{{ question.uuid }}">
							<blockquote>{{ question.text }}</blockquote>
							<div class="displayName">{{ question.display_name }}</div>
							<div class="votes"><span>{{ question.vote_count }}</span> {% trans "vote(s)" %}</div>
							<div class="createdAt">{{ question.created_at|date:"H:i" }}</div>
							<div class="questionActions">
								<button type="button" class="disapprove" data-state="new">{% trans "disapprove"|capfirst %}</button>
								<button type="button" class="approve" data-state="approved">{% trans "approve"|capfirst %}</button>
								<button type="button" class="markAnswered" data-state="answered">{% trans "mark as answered"|capfirst %}</button>
								<button type="button" class="markUnanswered" data-state="approved">{% trans "mark as unanswered"|capfirst %}</button>
								<button type="button" class="restore" data-state="new">{% trans "restore"|capfirst %}</button>
								<button type="button" class="discard" data-state="discarded">{% trans "discard"|capfirst %}</button>
							</div>
						</div>{% endfor %}
					</div>
				</details>{% endfor %}
			</div>
			<p>{% trans "To embed this Voxpop, copy the following and insert into your html:"|capfirst %}</p>
			<details id="embedCode">
				<summary>{%trans "embed code"|capfirst %}</summary>
				<button type="button" class="copyToClipboard">{% trans "copy"|capfirst %}</button>
				<pre><code class="html">&lt;div data-voxpop-uuid="{{ voxpop.uuid }}" data-voxpop-host="{{ request.META.HTTP_HOST }}"{% if not voxpop.allow_anonymous %} data-voxpop-login="{{idp}}"{% endif %}&gt;Afventer Voxpop…&lt;/div&gt;
&lt;script src="//{{ request.META.HTTP_HOST }}/static/voxpop.js"&gt;&lt;/script&gt;</code></pre>
				<p>{{ voxpop.allow_anonymous }}</p>
			</details>
			<p><a href="{% url 'voxpop:admin' %}">{% trans "return"|capfirst %}</a></p>
			<template id="questionTemplate">
				<div data-voxpop-question-uuid="">
					<blockquote><!-- text --></blockquote>
					<div class="displayName"><!-- display_name --></div>
					<div class="votes"><span>0</span> {% trans "vote(s)" %}</div>
					<div class="createdAt"><!-- created_at.time --></div>
					<div class="questionActions">
						<button type="button" class="disapprove" data-state="new">{% trans "disapprove"|capfirst %}</button>
						<button type="button" class="approve" data-state="approved">{% trans "approve"|capfirst %}</button>
						<button type="button" class="markAnswered" data-state="answered">{% trans "mark as answered"|capfirst %}</button>
						<button type="button" class="markUnanswered" data-state="approved">{% trans "mark as unanswered"|capfirst %}</button>
						<button type="button" class="restore" data-state="new">{% trans "restore"|capfirst %}</button>
						<button type="button" class="discard" data-state="discarded">{% trans "discard"|capfirst %}</button>
					</div>
				</div>
			</template>
			<script src="/static/admin.js"></script>
{% endblock %}